### ISSUE TITLE
Some potential improvements

### ISSUE THREAD

**Issue by mcouthon** [pdepip/mmap.it#15]
Hi,
first of all - I love the concept and the aesthetic. mmap is exactly the tool for me and my needs.
Having used it for all of 10 minutes, however, I have several suggestions:

1. Allow changing the default shortcut combinations. My `ctrl+space` combination is taken up by switching languages, which makes the search unusable (every time I open the search window, my language changes...)

2. Remember the location on screen. If I open mmap and move it to the center of the screen, close it and open it again, it is opened at the top-right corner of the screen again. In addition, it's not even fully visible when it appears—about 30% of its right side are beyond the limits of the screen.

3. Allow closing the search (i.e. dismissing the window) with `Esc`. Otherwise I'm forced to use the (somewhat uncomfortable, at least on my keyboard) `cmd + option + c` combination. (edit: just saw that I can use `cmd + w`, which is better, but IMO not as good as `Esc`).

4. Have a way to create a new note from inside the search menu. This would alleviate the need to often use 2 different shortcuts, as well as such being convenient in general.

5. When editing a new note, after losing focus, I need to press `cmd + option + c` twice to open the editing window again. I'm assuming this is because the window remains open in the background, instead of being dismissed upon losing focus.

All in all, though, awesome application! I'm definitely going to be using and recommending it. 👏

**Comment by pdepip** [comment]
Thank you so much for the kind words!  That really means a lot, glad to hear you're enjoying it and recommendations are always appreciated. 

In regards to your suggestions, I've created individual issues for each one and will start working on them asap.

1. #16  Something that has been on the roadmap, and will definitely be prioritized
2. #17 I actually did this intentionally but I can see why you would want to customize. I may add a config options that "remembers location". Also that's odd with it being 30% off the screen. What kind of mac/monitor are you using?
3. #19 Yes love this, should be a relatively straightforward change
4. #18 I really like this idea actually had not crossed my mind
5. #20 Definitely agree that is more straightforward than the current behavior. Will change asap

Again thank you for taking the time to send feedback I'm really excited to implement these and move the product forward.

**Comment by mcouthon** [comment]
Wow, thanks for the amazingly quick and thorough response! 

Regarding 2, here's a screenshot of how this looks in my screen:
![image](https://user-images.githubusercontent.com/844807/79359684-9195a680-7f4b-11ea-816f-79d15080b596.png)

I'm on Catalina 10.15.3, and this occurs both on my MacBook's screen and an external screen I use (a 27'' Dell 4k monitor).

I have some other thoughts, but I think I'll split them into separate issues, to allow you for easier tracking.

Again, amazing work. Thanks!

**Comment by mcouthon** [comment]
So I think this happens because I resized by window, and as it appears in the same coordinates by default, it hides whatever was resized.
I think this would be solved by #17.

**Comment by pdepip** [comment]
Ofcourse! Excited to push all of these features. Ok that totally makes sense, was trying to recreate yesterday on different monitors but had no luck. Hoping to have these fixes soon

**Comment by mcouthon** [comment]
Closing this one as all the points are already being addressed by specific issues 😃
