### ISSUE TITLE
[feature] Return focus after saving note

### ISSUE THREAD

**Issue by mcouthon** [pdepip/mmap.it#29]
In continuation to #24 (which now works perfectly, btw 🙏 ), it would also be very convenient if the previously in-focus window would return to focus after:
* Closing the search window with `cmd+w`
* Closing the compose window with `cmd+w`
* Saving a note with `cmd+s`

As always - a giant thanks for this awesome project! 💪

**Comment by pdepip** [comment]
Of course man! Really excited you're enjoying. It's funny as I pushed the change to fix this with search I realized I needed to fix it with saving notes as well. Thanks for making a ticket will get to this today

**Comment by mcouthon** [comment]
Hey, thanks a lot for getting to this - after saving the note the focus now returns to the previous window 👌 
But closing either the search or the compose windows with `cmd+w` still doesn't return the focus.
