### ISSUE TITLE
[bug] Title disappears after closing an unsaved note

### ISSUE THREAD

**Issue by mcouthon** [pdepip/mmap.it#30]
To reproduce:
1. `cmd+option+c` to start editing a note.
2. Add a title and some text in the note.
3. Close the note (either with `cmd+w` or `cmd+option+c`).
4. Open the note-editor again with `cmd+option+c` - you will see the unsaved note's text, but the title will be gone.

**Comment by pdepip** [comment]
Ty for steps to reproduce will fix this asap
