### ISSUE TITLE
[bug] Search does not look in note text - only title

### ISSUE THREAD

**Issue by mcouthon** [pdepip/mmap.it#31]
I _think_ it's a bug, since the docs say that the search is on the full text.

Here's an example note that I have:

![image](https://user-images.githubusercontent.com/844807/79636469-87a8b900-8180-11ea-9de3-488dca961487.png)

And here's me trying to search for the word `date` (which appears both in the code and in the heading):

![image](https://user-images.githubusercontent.com/844807/79636481-9f803d00-8180-11ea-8f99-e1701f42a3f2.png)

**Comment by pdepip** [comment]
Funny I noticed this exact thing with one of my own searches yesterday. I think this is because I have a threshold for minimum match score so even if you match a word, if it is a very long note it won't have a high enough score. I'll definitely fix that to make sure you see those
