### ISSUE TITLE
[feature] Allow pinning favorite notes

### ISSUE THREAD

**Issue by mcouthon** [pdepip/mmap.it#32]
Perhaps this won't jive with the minimalist approach of mmap, but I thought it could be useful to have a couple of pinned notes at the top of the search. Something like a to-do list, which you would to be able to access as quickly as possible would be perfect for this.

WDYT? :)

**Comment by pdepip** [comment]
Hmm let me think about this one. I definitely like the idea in the long term but not sure if it's the right time to put that in to the product. Can you think of other use cases outside of todo lists?

**Comment by mcouthon** [comment]
Well, I’m still trying to figure out all the usecases for mmap, and one thing I’m doing right now is keeping a note for my ongoing projects. This way I can very easily add a thought or a link to the note. It’s like a continuous brain dump, and mmap is perfect for it, because it’s always at your fingertips :)

I could maybe think of alternative solutions, like a dedicated shortcut to open a todo/inbox note in editing mode. 

Obviously, totally up to you :)

**Comment by pdepip** [comment]
ohh very interesting almost like a "speed dial" so to speak. So you can save long running notes to be easily accessible. I like that idea a lot

**Comment by mcouthon** [comment]
Yeah, exactly! It’s just the digital alternative of keeping a notebook by your side :)

**Comment by pdepip** [comment]
Ok so I've been thinking - what about a daily note feature that you can bring up with CMD + Option + D that will pin to the top of your search each day? It's kindof a combination of the pinning favorites and todo shortcut you were talking about

**Comment by mcouthon** [comment]
Yeah, that could work. And what would be the way to set it?
