### ISSUE TITLE
[bug] Browser window opened by clicking on link can't be moved

### ISSUE THREAD

**Issue by mcouthon** [pdepip/mmap.it#37]
This is how it looks for me:
![image](https://user-images.githubusercontent.com/844807/79695351-07b54880-827f-11ea-8ff3-a07ab0f365ba.png)

The browser window is opened behind the search window, and I can't move it from behind it.

And related to #36, I think that opening the links in the default browser is the more reasonable behavior.

**Comment by pdepip** [comment]
Yup! Fixing so it just opens link in default browser, good catch
