### ISSUE TITLE
[bug (?)] Opening the compose window shows previously opened note

### ISSUE THREAD

**Issue by mcouthon** [pdepip/mmap.it#39]
Steps to reproduce:
1. Open note (by searching + Enter).
2. Close window with `cmd+w`.
3. Open compose window with `cmd+option+c` (at this point closing/opening again with the same combination doesn't change anything).

I expected to see a clean note at this point, but saw the opened note from (1).

Solved by closing with `cmd+s` instead of `cmd+w`.

Very much a minor thing.

**Comment by pdepip** [comment]
hmm ok need to think about this one. So the original functionality was it would clear the note fully whenever you close the window with `cmd + option + c` (there is no current support for `cmd+w`). That obviously has issues if you're writing a long running note and want to hide it occasionally. 

You're definitely write though that after reading a note and closing it you dont want it to stay for the next time you open it..so there are a few options

**Comment by pdepip** [comment]
Would it make sense to check for "unsaved changes" on close - and if any exist - keep the note, but if the note is the same as before clear it? Need to thhink about this one

**Comment by mcouthon** [comment]
Yes, I think that's the perfect solution. Wouldn't want to lose unsaved
changes.
